/**
 * alertmanager
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Alertmanager);
  }
}(this, function(expect, Alertmanager) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Alertmanager.ChannelsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ChannelsApi', function() {
    describe('deletePolicyChannelsDelete', function() {
      it('should call deletePolicyChannelsDelete successfully', function(done) {
        //uncomment below and update the code to test deletePolicyChannelsDelete
        //instance.deletePolicyChannelsDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPolicyChannelsGet', function() {
      it('should call getPolicyChannelsGet successfully', function(done) {
        //uncomment below and update the code to test getPolicyChannelsGet
        //instance.getPolicyChannelsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPolicyChannelsGetAll', function() {
      it('should call getPolicyChannelsGetAll successfully', function(done) {
        //uncomment below and update the code to test getPolicyChannelsGetAll
        //instance.getPolicyChannelsGetAll(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postPolicyChannelsPost', function() {
      it('should call postPolicyChannelsPost successfully', function(done) {
        //uncomment below and update the code to test postPolicyChannelsPost
        //instance.postPolicyChannelsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postPolicyChannelsTest', function() {
      it('should call postPolicyChannelsTest successfully', function(done) {
        //uncomment below and update the code to test postPolicyChannelsTest
        //instance.postPolicyChannelsTest(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putPolicyChannelsPut', function() {
      it('should call putPolicyChannelsPut successfully', function(done) {
        //uncomment below and update the code to test putPolicyChannelsPut
        //instance.putPolicyChannelsPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
